# http://wiki.ros.org/navigation/Tutorials/RobotSetup
global_costmap:
  update_frequency: 5
  global_frame: map
  robot_base_frame: base_link
  publish_frequency: 5
  transform_tolerance: 0.5  # increased from 0.5 due to "unable to get starting pose of robot, unable to create global plan"
  width: 20
  height: 20
  origin_x: -10
  origin_y: -10
  static_map: false # Using a existing map -> true, else -> false
  rolling_window: true
  inflation_radius: 0.5 # seems to work well
  resolution: 0.1
  max_obstacle_height : 1
