# http://wiki.ros.org/navigation/Tutorials/RobotSetup
global_costmap:
  update_frequency: 5
  global_frame: map
  robot_base_frame: base_link
  publish_frequency: 5
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: false # Using a existing map -> true, else -> false
  rolling_window: true
  inflation_radius: 2
  resolution: 0.05