local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 1  # increased from 0.25 due to "unable to get starting pose of robot, unable to create global plan"
  static_map: false
  rolling_window: true
  width: 4
  height: 4
  origin_x: -2
  origin_y: -2
  resolution: 0.05
  inflation_radius: 0.4 # seems to work well

