# http://wiki.ros.org/navigation/Tutorials/RobotSetup
local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0  
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.05
  transform_tolerance: 0.25
  inflation_radius: 1.0