local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 1  # increased from 0.25 due to "unable to get starting pose of robot, unable to create global plan"
  static_map: false
  rolling_window: true
  width: 6
  height: 6
  origin_x: -3.5
  origin_y: -3.5
  resolution: 0.025
  inflation_radius: 0.1