# http://wiki.ros.org/navigation/Tutorials/RobotSetup
# Parameters: http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_rotational_vel: 0.3
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_rotational_vel: 0.5
  min_in_place_vel_theta: 0.5
  escape_vel: -0.1
  acc_lim_th: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  holonomic_robot: false

  